[package]
name = "kolenka"
version = "0.1.0"
edition = "2024"
authors = [
    "Vyacheslav Zalygin @vzalygin"
]

[dependencies]
lib = { path = "../lib" }

clap = { version = "4.5", features = ["derive"] }
colored = "3"
wasm-encoder = "0.245"
derived-deref = "2.1.0"
tempfile = "3"

[dev-dependencies]
wasmparser = "0.245"
